services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql

  bot:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/opt/bot

volumes:
  mysql_data:
  mysql_config:
